FROM php:8.1-fpm-alpine
WORKDIR /usr/share/nginx/html
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY www /usr/share/nginx/html

COPY --from=composer /usr/bin/composer /usr/local/bin/composer
RUN composer install
