version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site_lebbadi.rule=Host(`lebbadi.fr`) || Host(`www.lebbadi.fr`)"
      - "traefik.http.routers.site_lebbadi.tls=true"
      - "traefik.http.routers.site_lebbadi.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - traefik_default
      - default

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - default
      - postfix_default

networks:
  traefik_default:
    external: true
  postfix_default:
    external: true
