# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 753e7623d021e2b0a7eb0307d2dacd1e9c2cd1ede3d5375ebc0712cc0c966454754e5efdcb78b61ccdbf19c2f507106811bb7ef8797e32052f5828d9310e7cf9

test:
  secret_key_base: d46009113fb0b9242fbaf8d715a02b113c2cf9ff51ffe174dc444f9f7ad4cfebc749651ffdf4d21f652427f7033320890b3282294eee68807a37d3381a03f8a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
